name: worktime3
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

  cupertino_icons: ^1.0.2

  device_info_plus: ^11.4.0
  drag_and_drop_lists: ^0.4.2
  fab_circular_menu: ^1.0.2
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_native_splash:
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.2.0
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.6.1
  table_calendar: ^3.0.9
  url_launcher: ^6.1.10
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  freezed: ^3.0.6
  json_serializable: ^6.6.1
  riverpod_generator: ^2.6.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/ic_launcher.png"
  color: "2e2e2e"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"

adaptive_icon_background: "#ff0000"
adaptive_icon_foreground: "assets/images/ic_launcher.png"
